# 服务器配置
server:
  port: 18888
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
    connection-timeout: 5000

# Spring配置
spring:
  application:
    name: coder-gallery-backend

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coder_gallery?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: gzm2001..
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 9
    password:
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.leocoder.picture.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    call-setters-on-nulls: true
    return-instance-for-empty-row: true

# Sa-Token配置
sa-token:
  token-name: Authorization
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false
  is-print: false

# Knife4j API文档配置
knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: admin
    password: admin
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
    enable-version: false
    enable-reload-cache-parameter: false
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-filter-multipart-apis: false
    enable-request-cache: true
    enable-host: false
    enable-host-text: localhost:${server.port}
    enable-home-custom: false
    home-custom-path: classpath:markdown/home.md
    enable-search: true
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Copyright © 2023 Leo Coder

  # 安全配置
  security:
    # 不需要认证的路径
    permit-all:
      - /auth/login
      - /auth/register
      - /file/preview/**
      - /swagger-ui/**
      - /swagger-resources/**
      - /v3/api-docs/**
      - /webjars/**
      - /druid/**
      - /doc.html

  # 业务配置
  business:
    # 默认头像
    default-avatar: https://example.com/default-avatar.png
    # 图片处理相关
    image:
      # 最大图片尺寸限制
      max-width: 1920
      max-height: 1080
      # 支持的图片格式
      allowed-extensions: jpg,jpeg,png,gif,webp
      # 图片压缩质量(1-100)
      compress-quality: 85